### ISSUE TITLE
Error Handling Request during connexion

### ISSUE THREAD

**Issue by FaylenFR** [fsaris/home-assistant-awox#25] opened 2021-02-18 19:47 UTC
Hello, I am new in the configuration of Home assistant on RPI3, I tried to install your plugin with HACS but when I have to connect, the plugin says "Error unknown" and in the logs I have "Error Handling request".
I know that the identifiers are good I can check them directly on the mobile application
The screens with the details :
![image](https://user-images.githubusercontent.com/54444902/108413014-c7ba4b80-722a-11eb-94ef-448854aa24ca.png)
![image](https://user-images.githubusercontent.com/54444902/108413138-ea4c6480-722a-11eb-8619-17b64512f20a.png)
Awaiting your return, thank you in advance.

Yours sincerely,

**Comment by fsaris** [comment] 2021-02-18 20:51
Could you turn on debug logging and check the full logs? https://github.com/fsaris/home-assistant-awox#troubleshooting

**Comment by FaylenFR** [comment] 2021-02-18 21:13
This is
![image](https://user-images.githubusercontent.com/54444902/108422126-6dbf8300-7236-11eb-9ba6-1f74f5bd2315.png)

**Comment by fsaris** [comment] 2021-02-20 10:08
Somehow your second light doesn't have a `address` value.

Do you have 2 lights or more?

Because the 2 lights from the log are currently not supported as they use the zigbee protocol.

See #2

**Comment by FaylenFR** [comment] 2021-02-20 17:55
Yes I have 2 identical lights normally compatible with bluetooth and zigbee (for the remote control and the gateway)
I use it in bluetooth with my phone and I would like Home Assistant to do the same because I don't have for the moment an aWox gateway or a Zigbee key on my RPI3

So it's not compatible? will it ever be?

**Comment by fsaris** [comment] 2021-02-21 08:33
As I don't have such lights it's hard to get these supported as I can not test how these lights communicate.

I'm willing to add support but for me it's currently not possible to provide it

**Comment by fsaris** [comment] 2021-02-22 06:46
Duplicate of #2

**Closed by fsaris** 2021-02-22 06:46 UTC
